"use client";

import { CaseCard } from "@/components/incidents/CaseCard";
import { StatTile } from "@/components/StatTile";
import { useLiveCases } from "@/lib/incidents/useLiveCases";

export default function IncidentsPage() {
  const { cases, connected } = useLiveCases();

  const activeCases = cases.filter((c) => c.active);
  const analyzed = cases.filter((c) => c.time_to_insight_seconds !== null);
  const avgTimeToInsight =
    analyzed.length > 0
      ? analyzed.reduce((sum, c) => sum + (c.time_to_insight_seconds ?? 0), 0) / analyzed.length
      : null;
  const highSeverityCount = cases.filter((c) => c.severity === "high").length;

  return (
    <div className="px-6 py-10 md:px-12 lg:px-20 max-w-[1000px] mx-auto">
      <header className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mb-8">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">AI Payments Incident Copilot</h1>
          <p className="text-secondary text-sm mt-1">
            Watches the observability module&apos;s live telemetry, and uses an LLM to
            independently diagnose likely root cause the moment a channel degrades — without ever
            being told what the injected fault actually was.
          </p>
        </div>
        <div className="flex items-center gap-2 text-sm shrink-0">
          <span
            className="inline-block w-2 h-2 rounded-full"
            style={{ background: connected ? "var(--status-good)" : "var(--status-critical)" }}
            aria-hidden
          />
          <span className="text-secondary">{connected ? "Live" : "Reconnecting…"}</span>
        </div>
      </header>

      <section className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <StatTile label="Cases analyzed" value={String(cases.length)} />
        <StatTile label="Currently active" value={String(activeCases.length)} />
        <StatTile
          label="Avg. time to insight"
          value={avgTimeToInsight !== null ? `${avgTimeToInsight.toFixed(1)}s` : "—"}
          sublabel="detection → AI diagnosis"
        />
        <StatTile label="High severity" value={String(highSeverityCount)} />
      </section>

      <section className="flex flex-col gap-4">
        {cases.length === 0 && (
          <div className="card p-8 text-center text-muted text-sm">
            No incidents yet — this platform only opens a case when a channel actually degrades.
            Check back shortly; the observability module injects incidents periodically.
          </div>
        )}
        {cases.map((c) => (
          <CaseCard key={c.id} c={c} />
        ))}
      </section>

      <footer className="mt-12 text-muted text-xs">
        Diagnoses are generated by an LLM from live synthetic telemetry and may be wrong — this is
        a demonstration of an AI-assisted triage workflow, not a production incident response tool.
      </footer>
    </div>
  );
}
