"use client";

import { AlertTriangle, Clock, Flame, ListChecks } from "lucide-react";
import { CaseCard } from "@/components/incidents/CaseCard";
import { RailBreakdown } from "@/components/incidents/RailBreakdown";
import { StatTile } from "@/components/StatTile";
import { JARGON } from "@/lib/glossary";
import { useLiveCases } from "@/lib/incidents/useLiveCases";

export default function IncidentsPage() {
  const { cases, connected } = useLiveCases();

  const activeCases = cases.filter((c) => c.active);
  const analyzed = cases.filter((c) => c.time_to_insight_seconds !== null);
  const avgTimeToInsight =
    analyzed.length > 0
      ? analyzed.reduce((sum, c) => sum + (c.time_to_insight_seconds ?? 0), 0) / analyzed.length
      : null;
  const highSeverityCount = cases.filter((c) => c.severity === "high").length;

  return (
    <div className="px-6 py-10 md:px-12 lg:px-20 max-w-[1000px] mx-auto">
      <header className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mb-8">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">AI Payments Incident Copilot</h1>
          <p className="text-secondary text-sm mt-1">
            Watches telemetry across every rail — card, wire (including LoanIQ, batch, and
            IVR-originated wires), ACH, and Zelle — and uses an LLM to independently diagnose
            likely root cause the moment a channel degrades, without ever being told what the
            injected fault actually was.
          </p>
        </div>
        <div
          className="badge shrink-0"
          style={{
            background: connected
              ? "color-mix(in srgb, var(--status-good) 14%, transparent)"
              : "color-mix(in srgb, var(--status-critical) 14%, transparent)",
            color: connected ? "var(--status-good)" : "var(--status-critical)",
          }}
        >
          <span
            className="inline-block w-1.5 h-1.5 rounded-full"
            style={{ background: connected ? "var(--status-good)" : "var(--status-critical)" }}
            aria-hidden
          />
          {connected ? "Live" : "Reconnecting…"}
        </div>
      </header>

      <div
        className="flex items-center gap-2.5 text-xs rounded-md px-3 py-2.5 mb-8"
        style={{
          background: "color-mix(in srgb, var(--status-warning) 12%, transparent)",
          color: "var(--text-secondary)",
        }}
      >
        <AlertTriangle size={15} strokeWidth={2} style={{ color: "var(--status-warning)" }} className="shrink-0" />
        <span>
          <strong className="font-medium" style={{ color: "var(--text-primary)" }}>AI-generated hypothesis, not verified.</strong>{" "}
          Every diagnosis below is produced by an LLM reasoning over live telemetry — treat it as a
          first-pass lead for a human on-call engineer, not a confirmed root cause.
        </span>
      </div>

      <section className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <StatTile label="Cases analyzed" value={String(cases.length)} icon={ListChecks} />
        <StatTile label="Currently active" value={String(activeCases.length)} icon={Flame} />
        <StatTile
          label="Avg. time to insight"
          value={avgTimeToInsight !== null ? `${avgTimeToInsight.toFixed(1)}s` : "—"}
          sublabel="detection → AI diagnosis"
          tooltip={JARGON.timeToInsight}
          icon={Clock}
        />
        <StatTile label="High severity" value={String(highSeverityCount)} icon={AlertTriangle} />
      </section>

      <section className="mb-8">
        <RailBreakdown cases={cases} />
      </section>

      <section className="flex flex-col gap-4">
        {cases.length === 0 && (
          <div className="card p-8 text-center text-muted text-sm">
            No incidents yet — this platform only opens a case when a channel actually degrades.
            Check back shortly; the observability module injects incidents periodically.
          </div>
        )}
        {cases.map((c) => (
          <CaseCard key={c.id} c={c} />
        ))}
      </section>

      <footer className="mt-12 text-muted text-xs">
        Diagnoses are generated by an LLM from live synthetic telemetry and may be wrong — this is
        a demonstration of an AI-assisted triage workflow, not a production incident response tool.
      </footer>
    </div>
  );
}
